### ISSUE TITLE
test data is changed during scoring

### ISSUE THREAD

**Issue by ottowg** [sheffieldnlp/fever-scorer#1]
Hello,
if you use different parameters for max_evidence the dataset will be changed (predicted_evidence is cut to max_evidence)

This creates strange behavior:
Here the example from the readme:

``test = {"label": "REFUTES", "predicted_label": "refutes", "predicted_evidence": [
        ["page1", 1],                                   
        ["page2", 2],
        ["page3", 3]                                    
    ], 
    "evidence":
    [
        [
            [None, None, "page1", 1],   
            [None, None, "page2", 2],
        ]
    ]
}
test_set = [test]
print(fever_scorer.fever_score(test_set, max_evidence=3))
print(fever_scorer.fever_score(test_set, max_evidence=2))
print(fever_scorer.fever_score(test_set, max_evidence=1))

print(fever_scorer.fever_score(test_set, max_evidence=1))
print(fever_scorer.fever_score(test_set, max_evidence=2))
print(fever_scorer.fever_score(test_set, max_evidence=3))

print(fever_scorer.fever_score(test_set, max_evidence=3))
print(fever_scorer.fever_score(test_set, max_evidence=2))
print(fever_scorer.fever_score(test_set, max_evidence=1))``

will output:
(1.0, 1.0, 0.6666666666666666, 1.0, 0.8)
(1.0, 1.0, 1.0, 1.0, 1.0)
(0.0, 1.0, 1.0, 0.0, 0.0)
(0.0, 1.0, 1.0, 0.0, 0.0)
(0.0, 1.0, 1.0, 0.0, 0.0)
(0.0, 1.0, 1.0, 0.0, 0.0)
(0.0, 1.0, 1.0, 0.0, 0.0)
(0.0, 1.0, 1.0, 0.0, 0.0)
(0.0, 1.0, 1.0, 0.0, 0.0)

So you are not able to reproduce the measured scores.

The error is in line 34 in
 fever-scorer/src/fever/scorer.py I think.

Thanks: Wolf

**Comment by j6mes** [comment]
Hi, thanks for submitting this. Yes, this is an issue, and it was a use-case I hadn't expected. I've added a fix and a test to check non-modification of the predicted evidence in f6584e2.

Hope this helps. 
J
